name: fmt

on: [push]

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.13.5
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: '.'
          tf_actions_comment: 'true'
          args: '-recursive'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
